
import { MarketItem, TranslationKeys, Language } from './types';

export const MOCK_MARKET_DATA: MarketItem[] = [
  { id: '1', symbol: 'XAU/USD', name: 'Gold', price: 2034.50, change: 0.45, type: 'commodity', lastUpdated: '10:05 AM', data: [2020, 2025, 2022, 2030, 2034.50] },
  { id: '2', symbol: 'VN30', name: 'VN30 Index', price: 1150.2, change: 0.8, type: 'etf', lastUpdated: '10:00 AM', data: [1140, 1142, 1145, 1148, 1150.2] },
  { id: '3', symbol: 'BTC/USD', name: 'Bitcoin', price: 42100, change: 2.1, type: 'crypto', lastUpdated: '10:06 AM', data: [41000, 41500, 41200, 41800, 42100] },
  { id: '4', symbol: 'ETH/USD', name: 'Ethereum', price: 2250.40, change: 1.5, type: 'crypto', lastUpdated: '10:07 AM', data: [2200, 2220, 2210, 2240, 2250.40] },
  { id: '5', symbol: 'EUR/USD', name: 'Euro', price: 1.09, change: -0.1, type: 'forex', lastUpdated: '10:05 AM', data: [1.10, 1.095, 1.092, 1.088, 1.09] },
  { id: '6', symbol: 'XAG/USD', name: 'Silver', price: 22.80, change: -1.2, type: 'commodity', lastUpdated: '10:05 AM', data: [23, 22.9, 22.85, 22.7, 22.8] },
  { id: '7', symbol: 'CL=F', name: 'Crude Oil', price: 72.50, change: -2.3, type: 'commodity', lastUpdated: '09:55 AM', data: [75, 74.2, 73.5, 73.0, 72.5] },
  { id: '8', symbol: 'SPX', name: 'S&P 500', price: 4780.20, change: 0.3, type: 'etf', lastUpdated: '10:00 AM', data: [4750, 4760, 4755, 4770, 4780.20] },
  { id: '9', symbol: 'AAPL', name: 'Apple Inc.', price: 185.92, change: 0.5, type: 'etf', lastUpdated: '09:45 AM', data: [182, 183, 184, 185, 185.92] },
  { id: '10', symbol: 'TSLA', name: 'Tesla Inc.', price: 215.55, change: -2.1, type: 'etf', lastUpdated: '09:45 AM', data: [225, 222, 220, 218, 215.55] },
  { id: '11', symbol: 'NVDA', name: 'Nvidia', price: 545.2, change: 3.2, type: 'etf', lastUpdated: '09:45 AM', data: [530, 535, 538, 542, 545.2] },
  { id: '12', symbol: 'VCB', name: 'Vietcombank', price: 89500, change: 0.1, type: 'etf', lastUpdated: '10:00 AM', data: [89000, 89200, 89100, 89400, 89500] },
  { id: '13', symbol: 'HPG', name: 'Hoa Phat', price: 28100, change: 1.1, type: 'etf', lastUpdated: '10:00 AM', data: [27500, 27800, 27900, 28000, 28100] },
  { id: '14', symbol: 'SOL/USD', name: 'Solana', price: 92.40, change: 4.5, type: 'crypto', lastUpdated: '10:10 AM', data: [85, 88, 87, 90, 92.4] },
  { id: '15', symbol: 'BNB/USD', name: 'Binance Coin', price: 312.50, change: -0.4, type: 'crypto', lastUpdated: '10:10 AM', data: [315, 314, 313, 312, 312.5] },
  { id: '16', symbol: 'XRP/USD', name: 'Ripple', price: 0.57, change: 0.9, type: 'crypto', lastUpdated: '10:10 AM', data: [0.55, 0.56, 0.56, 0.57, 0.57] },
  { id: '17', symbol: 'USD/JPY', name: 'USD/JPY', price: 147.5, change: 0.2, type: 'forex', lastUpdated: '10:05 AM', data: [146, 146.5, 147, 147.2, 147.5] },
  { id: '18', symbol: 'GBP/USD', name: 'GBP/USD', price: 1.27, change: -0.05, type: 'forex', lastUpdated: '10:05 AM', data: [1.28, 1.275, 1.272, 1.27, 1.27] },
];

const TEXT_RESOURCES: Record<TranslationKeys, [string, string]> = {
  'nav.home': ['Trang chủ', 'Home'],
  'nav.markets': ['Thị trường', 'Markets'],
  'nav.calculators': ['Công cụ tính', 'Calculators'],
  'nav.portfolio': ['Danh mục', 'Portfolio'],
  'nav.income_split': ['Phân bổ thu nhập', 'Income Split'],
  'nav.login': ['Đăng nhập', 'Login'],
  'nav.register': ['Đăng ký', 'Register'],
  'nav.logout': ['Đăng xuất', 'Logout'],
  'common.loading': ['Đang tải...', 'Loading...'],
  'common.error': ['Có lỗi xảy ra', 'An error occurred'],
  'common.save': ['Lưu', 'Save'],
  'common.submit': ['Gửi', 'Submit'],
  'common.theme': ['Giao diện', 'Theme'],
  'common.cancel': ['Hủy', 'Cancel'],
  'common.disclaimer': ['Miễn trừ trách nhiệm: Dữ liệu chỉ mang tính tham khảo.', 'Disclaimer: Data provided for informational purposes only.'],
  'common.updated': ['Cập nhật', 'Updated'],
  'common.login_required': ['Vui lòng đăng nhập.', 'Login required.'],
  'common.back': ['Quay lại', 'Back'],
  'common.search_placeholder': ['Tìm kiếm mã hoặc tên...', 'Search symbol or name...'],
  'common.clear_filters': ['Xóa bộ lọc', 'Clear filters'],
  'common.no_data': ['Không tìm thấy dữ liệu.', 'No market data found.'],
  'home.snapshot': ['Thị trường trực tuyến', 'Live Market Snapshot'],
  'home.quick_actions': ['Truy cập nhanh', 'Quick Actions'],
  'home.intro': ['GenZF tổng hợp dữ liệu thời gian thực từ các sàn giao dịch toàn cầu.', 'GenZF aggregates real-time data from global exchanges.'],
  'home.feat.profit': ['Tính Lợi Nhuận', 'Profit Calculator'],
  'home.feat.profit_desc': ['Tính ROI tiềm năng & lợi nhuận.', 'Calculate potential ROI & returns.'],
  'home.feat.tax': ['Tính Thuế TNCN', 'Income Tax Estimator'],
  'home.feat.tax_desc': ['Ước tính nghĩa vụ thuế thu nhập.', 'Estimate personal income tax.'],
  'home.feat.markets': ['Thị trường', 'Explore Markets'],
  'home.feat.markets_desc': ['Khám phá xu hướng thị trường toàn cầu.', 'Explore global market trends.'],
  'home.feat.portfolio': ['Danh mục', 'Portfolio'],
  'home.feat.portfolio_guest': ['Đăng nhập để theo dõi tài sản.', 'Log in to track your assets.'],
  'home.feat.portfolio_user': ['Theo dõi tài sản và hiệu suất.', 'Track your assets and performance.'],
  'market.subtitle': ['Theo dõi giá thời gian thực.', 'Track real-time prices.'],
  'market.filter_all': ['Tất cả', 'All Markets'],
  'market.filter_crypto': ['Tiền số', 'Crypto'],
  'market.filter_forex': ['Ngoại hối', 'Forex'],
  'market.filter_commodity': ['Hàng hóa', 'Commodities'],
  'market.filter_etf': ['ETF & Cổ phiếu', 'ETFs & Stocks'],
  'market.sort_change_desc': ['% Tăng (Cao -> Thấp)', '% Change (High to Low)'],
  'market.sort_change_asc': ['% Tăng (Thấp -> Cao)', '% Change (Low to High)'],
  'market.sort_price_desc': ['Giá (Cao -> Thấp)', 'Price (High to Low)'],
  'market.sort_price_asc': ['Giá (Thấp -> Cao)', 'Price (Low to High)'],
  'market.sort_name': ['Tên (A-Z)', 'Name (A-Z)'],
  'market.status_title': ['Trạng thái thị trường', 'Market Status'],
  'market.status_desc': ['Thị trường đang Mở cửa.', 'Market is currently Open.'],
  'market.open': ['Mở cửa', 'Open'],
  'market.high': ['Cao nhất', 'High'],
  'market.low': ['Thấp nhất', 'Low'],
  'market.vol': ['KLGD', 'Volume'],
  'market.tab_chart': ['Biểu đồ', 'Chart'],
  'market.tab_overview': ['Tổng quan', 'Overview'],
  'market.tab_calc': ['Tính lãi', 'Profit Calc'],
  'market.not_found': ['Không tìm thấy', 'Market Not Found'],
  'calc.profit.title': ['Tính Lợi Nhuận', 'Profit Calculator'],
  'calc.profit.buy_price': ['Giá mua', 'Buy Price'],
  'calc.profit.sell_price': ['Giá bán', 'Sell Price'],
  'calc.profit.qty': ['Số lượng', 'Quantity'],
  'calc.profit.result': ['Lợi nhuận ròng', 'Net Profit/Loss'],
  'calc.profit.breakeven': ['Hòa vốn', 'Break-even'],
  'calc.tax.title': ['Tính Thuế TNCN', 'Income Tax Estimator'],
  'calc.tax.income': ['Thu nhập tháng (VND)', 'Monthly Income (VND)'],
  'calc.tax.calculate': ['Tính thuế', 'Calculate Tax'],
  'calc.tax.est_tax': ['Thuế ước tính', 'Estimated Tax'],
  'calc.tax.net_income': ['Thu nhập ròng', 'Net Income'],
  'calc.tax.disclaimer': ['Mô phỏng dựa trên biểu thuế lũy tiến.', 'Mock calculation based on general rates.'],
  'port.title': ['Danh mục của tôi', 'My Portfolio'],
  'port.welcome': ['Chào mừng trở lại', 'Welcome back'],
  'port.add_trans': ['Thêm giao dịch', 'Add Transaction'],
  'port.allocation': ['Phân bổ tài sản', 'Asset Allocation'],
  'port.net_worth': ['Tổng tài sản ròng', 'Total Net Worth'],
  'port.all_time': ['Từ trước đến nay', 'All time'],
  'port.table.asset': ['Tài sản', 'Asset'],
  'port.table.qty': ['Số lượng', 'Qty'],
  'port.table.avg': ['Giá TB', 'Avg Cost'],
  'port.table.cur': ['Giá hiện tại', 'Current Price'],
  'port.table.pl': ['Lãi/Lỗ', 'P/L'],
  'port.table.action': ['Hành động', 'Action'],
  'port.modal.title': ['Thêm giao dịch mới', 'Add New Transaction'],
  'port.modal.symbol': ['Mã tài sản', 'Asset Symbol'],
  'port.modal.qty': ['Số lượng', 'Quantity'],
  'port.modal.price': ['Giá mua (VND)', 'Buy Price (VND)'],
  'port.modal.add': ['Thêm vào danh mục', 'Add to Portfolio'],
  'port.close': ['Xóa tài sản', 'Remove Asset'],
  'port.remove_confirm': ['Xóa vị thế này khỏi danh mục?', 'Remove this position from portfolio?'],
  'port.verified_asset': ['Tài sản xác thực', 'Verified Asset'],
  'port.spot_market': ['Giao dịch giao ngay', 'Spot Market'],
  'port.valuation_realtime': ['Định giá thời gian thực', 'Real-time valuation'],
  'port.growth_perf': ['Hiệu suất tăng trưởng', 'Growth Performance'],
  'port.pl_perf': ['Hiệu suất Lãi/Lỗ', 'P/L PERFORMANCE'],
  'port.profit_status': ['LỢI NHUẬN', 'PROFIT'],
  'port.loss_status': ['THUA LỖ', 'LOSS'],
  'port.strategy_title': ['Chiến lược danh mục của bạn', 'Your Portfolio Strategy'],
  'port.strategy_desc': ['Giá tài sản được tổng hợp từ các sàn giao dịch toàn cầu để cung cấp P/L tham khảo.', 'Asset prices are aggregated from global exchanges to provide real-time indicative P/L.'],
  'port.explore_markets': ['KHÁM PHÁ THỊ TRƯỜNG', 'EXPLORE MARKETS'],
  'port.active_positions': ['vị thế đang mở', 'active positions'],
  'port.total_assets': ['Tổng tài sản', 'Total Assets'],
  'port.leader': ['Dẫn đầu', 'Leader'],
  'port.strategy_insight': ['Phân tích chiến lược', 'Strategy Insight'],
  'port.live_tracking': ['Theo dõi trực tiếp', 'Live Tracking'],
  'port.assets_label': ['Tài sản', 'Assets'],
  'split.title': ['Quy tắc 50/30/20', '50/30/20 Rule Planner'],
  'split.subtitle': ['Điều chỉnh thanh trượt để phân bổ thu nhập tháng.', 'Adjust the sliders to allocate your monthly income.'],
  'split.income': ['Thu nhập tháng', 'Monthly Income'],
  'split.unallocated': ['Chưa phân bổ', 'Unallocated'],
  'split.needs': ['NHU CẦU', 'NEEDS'],
  'split.needs_desc': ['Thuê nhà, Ăn uống, Điện nước', 'Rent, Groceries, Utilities'],
  'split.wants': ['MONG MUỐN', 'WANTS'],
  'split.wants_desc': ['Ăn ngoài, Giải trí, Sở thích', 'Dining, Entertainment, Hobbies'],
  'split.save': ['TIẾT KIỆM', 'SAVE'],
  'split.save_desc': ['Đầu tư, Quỹ khẩn cấp', 'Investments, Emergency Fund'],
  'split.reset': ['Mặc định', 'Reset Defaults'],
  'split.save_plan': ['Lưu kế hoạch', 'Save Plan'],
  'split.success': ['Đã lưu thành công!', 'Plan saved successfully!'],
  'split.visualizer': ['Bộ trực quan phân bổ', 'Allocation Visualizer'],
  'split.fully_allocated': ['Đã phân bổ hết', 'Fully Allocated'],
  'split.pro_tip': ['Lời khuyên tài chính', 'Financial Pro Tip'],
  'split.pro_tip_desc': ['Bằng cách đầu tư mỗi tháng, bạn đang xây dựng tự do tài chính dài hạn.', 'By investing every month, you are building long-term financial freedom.'],
  'auth.email': ['Địa chỉ Email', 'Email Address'],
  'auth.password': ['Mật khẩu', 'Password'],
  'auth.forgot_password': ['Quên mật khẩu?', 'Forgot Password?'],
  'auth.remember_me': ['Ghi nhớ đăng nhập', 'Remember me'],
  'auth.login_title': ['Chào mừng trở lại', 'Welcome back'],
  'auth.login_subtitle': ['Nhập thông tin xác thực để truy cập.', 'Enter your credentials to access your account.'],
  'auth.register_title': ['Tạo tài khoản mới', 'Create an account'],
  'auth.register_subtitle': ['Bắt đầu theo dõi danh mục ngay hôm nay.', 'Start tracking your portfolio today.'],
  'auth.name': ['Họ và tên', 'Full Name'],
  'auth.confirm_password': ['Xác nhận mật khẩu', 'Confirm Password'],
  'auth.have_account': ['Đã có tài khoản?', 'Already have an account?'],
  'auth.no_account': ['Chưa có tài khoản?', 'Don\'t have an account?'],
  'auth.reset_password': ['Đặt lại mật khẩu', 'Reset Password'],
  'auth.back_to_login': ['Quay lại đăng nhập', 'Back to login'],
  'auth.sent_title': ['Kiểm tra email', 'Check your email'],
  'auth.sent_desc': ['Chúng tôi đã gửi liên kết đặt lại mật khẩu.', 'We have sent a password reset link to your email address.'],
};

export const TRANSLATIONS: Record<Language, Record<TranslationKeys, string>> = {
  vi: Object.fromEntries(Object.entries(TEXT_RESOURCES).map(([k, v]) => [k, v[0]])) as Record<TranslationKeys, string>,
  en: Object.fromEntries(Object.entries(TEXT_RESOURCES).map(([k, v]) => [k, v[1]])) as Record<TranslationKeys, string>,
};
